In [5]:
import numpy as np
import sympy as sp 

In [ ]:
# Let's define the matrix 
A = [
  [1, 2, 3, 4, 5],
  [2, 4, 6, 8, 10],
  [1, 0, 1, 0, 1],
  [3, 6, 9, 12, 15]
]

In [6]:
A_sp = sp.Matrix([
    [1,2,3,4,5],
    [2, 4, 6, 8, 10],
  [1, 0, 1, 0, 1],
  [3, 6, 9, 12, 15]
])

In [7]:
print(A_sp)

Matrix([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [1, 0, 1, 0, 1], [3, 6, 9, 12, 15]])


Question 1:
 Column Space (C(A))
   - Find a basis for the column space of A.
   - What is the dimension of the column space?
   - What does this tell you about the effective number of features?

In [8]:
def column_space(A, tol=1e-10):
    Q, R = np.linalg.qr(A)
    rank = np.linalg.matrix_rank(R, tol=tol)
    return Q[:, :rank]

print("Column Space Basis:")
print(column_space(A))

Column Space Basis:
[[-0.25819889 -0.06900656]
 [-0.51639778 -0.13801311]
 [-0.25819889  0.96609178]
 [-0.77459667 -0.20701967]]


In [9]:
# Column space calculation using sympy library 
column_space_basis = A_sp.columnspace()

In [15]:
for vec in column_space_basis:
    sp.pprint(vec)

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣3⎦
⎡2⎤
⎢ ⎥
⎢4⎥
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣6⎦


From the above result we can infer that the dimension of column space is 4 * 2.
And also out of 5 columns, only 2 are effective and give varying directions

Question 2:
Null Space (N(A))
   - Find a basis for the null space of A, i.e., solve A·x = 0.
   - Interpret this in terms of feature redundancy.

In [12]:
null_space = A_sp.nullspace()
for vec in null_space:
    sp.pprint(vec)

⎡-1⎤
⎢  ⎥
⎢-1⎥
⎢  ⎥
⎢1 ⎥
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎣0 ⎦
⎡0 ⎤
⎢  ⎥
⎢-2⎥
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎢1 ⎥
⎢  ⎥
⎣0 ⎦
⎡-1⎤
⎢  ⎥
⎢-2⎥
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎣1 ⎦


Question 3

In [16]:
row_space = A_sp.rowspace()
for vec in row_space:
    sp.pprint(row_space)

[[1  2  3  4  5], [0  -2  -2  -4  -4]]
[[1  2  3  4  5], [0  -2  -2  -4  -4]]


Question 4

In [22]:
print("Left Null Space Basis:")
left_null_space = A_sp.T.nullspace()
for vec in left_null_space:
    sp.pprint(vec)


Left Null Space Basis:
⎡-2⎤
⎢  ⎥
⎢1 ⎥
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎣0 ⎦
⎡-3⎤
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎣1 ⎦
